
Object subclass: #MetacelloToolBox
	instanceVariableNames: 'project methodSpec'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Metacello-ToolBox'!

!MetacelloToolBox commentStamp: '<historical>' prior: 0!
MetacelloToolbox implements a toolbox API for Metacello.

The toolbox methods on the class-side implement scripts for a number of commonly performed Metacello development tasks. The methods should be used in development scripts or GUI tools so that a common implementation is preserved across the toolset.!
