
Object subclass: #MetacelloScriptEngine
	instanceVariableNames: 'root projectName projectClass repositoryDescription versionString personalRepositories personal platformOverrides platformRepositories goferCache pinnedProjects'
	classVariableNames: 'DefaultMetacelloRepositoryDescription PersonalRepositories PinnedProjects PlatformOverrides'
	poolDictionaries: ''
	category: 'Metacello-Core-Scripts'!
